version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=laravel
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    networks:
      - app-net
  web:
    image: laravel-sample-pack:latest
    environment:
      - DB_HOST=db
      - LAUNCH_TYPE=local
      - OPTION=php artisan migrate
    ports:
      - 80:8080
    depends_on:
      - db
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
